# Generated by Django 5.0.3 on 2024-04-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='usertable',
        ),
    ]
